### PR TITLE
submit week4 assessment

### PR DESCRIPTION
**Pull request by ajiboyeazeezat**

### CODE REVIEW

**Review by emetowinner — APPROVED** [review]
Nice work Ajiboye, am yet to get your Assessment for weeks 1,2, and 3. Why?

**Comment by ajiboyeazeezat** [comment]
Thank you sir, I already submitted them. It was sent to yourmail.

**Comment by ajiboyeazeezat** [comment]
Acknowledged sir

**Comment by ajiboyeazeezat** [comment]
Dear Winner,

Trust you’re doing well? I’m messaging to inform you that I’m unable to
submit my assignment as required of me because I’m currently sick and on
admission in the hospital.

I’ll ensure that the assignment is submitted as soon as possible once I’m
better.

Thank you so much.

Kind Regards,
Azeezat.

**Pull request merged**
